# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b29b710b65e15ad08a3723efe8261279"
name = "gserra-checkout"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "gserra-checkout"

[build]
include_config_on_deploy = true
dev_store_url = "gserra-test.myshopify.com"

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
